network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      dhcp4: false
      dhcp6: false
      addresses: [192.168.0.123/24]
      gateway4: 192.168.0.1
      nameservers:
        addresses: [192.168.0.1]
