#!/bin/bash

# install nodenv
git clone https://github.com/nodenv/nodenv.git ~/.nodenv
echo 'export PATH="$HOME/.nodenv/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(nodenv init -)"' >> ~/.zshrc
source ~/.zshrc

# install node-build
git clone https://github.com/nodenv/node-build.git $(nodenv root)/plugins/node-build

# check nodenv
curl -fsSL https://github.com/nodenv/nodenv-installer/raw/master/bin/nodenv-doctor | zsh
